!classDefinition: #Pepe category: 'Ejercicio1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: 'Ejercicio1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'Pepe' stamp: 'ml 3/21/2025 15:22:59'!
hola
	^'chau'! !
