!classDefinition: #Pepe category: 'Seccion1Part1Ejercicio1: saludo'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Seccion1Part1Ejercicio1: saludo'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: 'Seccion1Part1Ejercicio1: saludo'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'as yet unclassified' stamp: 'ml 8/21/2024 13:44:58'!
hola
	^'chau'! !
